services:
  celery:
    image: tf_01/f5mobile-cms:latest
    env_file:
      - .env
    command: celery -A workers.tasks worker --loglevel=INFO

  backend:
    image: tf_01/f5mobile-cms:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - celery
    command:
      [
        "uvicorn",
        "main:app",
        "--port",
        "8000",
        "--host",
        "0.0.0.0"
      ]
